# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6be83af5911444dcd6753c454485c6950692f0f2b84e7218f791c0be75bf0b2ea9773ae79127d77d4e27c2f6b415aac68c787799a1970b49d5c4c4407a4330dd

test:
  secret_key_base: 496c7ae8127d619ed0033197ebbf14c46444fc6be85584c7b629376fceda70d45b022d1f52dca73ed8f7578a8492d52ad7323d03978ae907367b7525c4f65d9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
